WebTimes_MVC/Models/Times.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebTimes_MVC.Models
{
    public class Times
    {
        [Display(Name = "ID")]
        public int TimeId { get; set; }

        [Required(ErrorMessage = "Digite o time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Informe o estado")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "Informe as cores do time")]
        public string Cores { get; set; }
    }
}

WebTimes_MVC/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTimes_MVC.Repositorio;
using WebTimes_MVC.Models;

namespace WebTimes_MVC.Controllers
{
    public class TimeController : Controller
    {
        private TimesRepositorio _repositorio;

        // GET: Time
        public ActionResult ObterTimes()
        {
            _repositorio = new TimesRepositorio();
            ModelState.Clear();
            return View(_repositorio.ObterTimes());
        }

        public ActionResult IncluirTime()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IncluirTime(Times timeObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio = new TimesRepositorio();

                    if (_repositorio.AdicionarTime(timeObj))
                    {
                        ViewBag.Mensagem = "Time cadastrado com sucesso!!";
                    }
                }

                return View();
            }
            catch (Exception ex)
            {
                return View("ObterTimes");
            }
        }


        public ActionResult EditarTime(int id)
        {
            _repositorio = new TimesRepositorio();
            return View(_repositorio.ObterTimes().Find(t => t.TimeId == id));
        }

        [HttpPost]
        public ActionResult EditarTime(int id,Times timeObj)
        {
            try
            {
                _repositorio = new TimesRepositorio();

                _repositorio.AtualizarTime(timeObj);

                return RedirectToAction("ObterTimes");
            }catch (Exception ex)
            {
                return View("ObterTimes");
            }
        }

        public ActionResult ExcluirTime(int id)
        {
            try
            { 
                _repositorio = new TimesRepositorio();
                if (_repositorio.ExcluirTime(id))
                {
                    ViewBag.Mensagem = "Time excluído com sucesso!!";
                }

                return RedirectToAction("ObterTimes");
            }catch (Exception ex)
            {
                return View("ObterTimes");
            }
        }
    }
}

WebTimes_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Times Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Times", "ObterTimes", "Time", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "ObterTimes", "Time")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Times Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebTimes_MVC/Views/Time/EditarTime.cshtml
@model WebTimes_MVC.Models.Times

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atualizar Time</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TimeId)

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
            </div>
        </div>

       
    </div>
}

<div>
    @Html.ActionLink("Voltar", "ObterTimes")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebTimes_MVC/Views/Time/IncluirTime.cshtml
@model WebTimes_MVC.Models.Times

@{
    ViewBag.Title = "Incluir Time";
}

<h2>Incluir Time</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Times</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Mensagem
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Voltar", "ObterTimes")
</div>

<!-- Script para validar se os campos são vazios no client, sem precisar dar o post no servidor-->
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebTimes_MVC/Views/Time/ObterTimes.cshtml
@model IEnumerable<WebTimes_MVC.Models.Times>

<h4>Todos os Times</h4>
<p>
    @Html.ActionLink("Adicionar Novo Time", "IncluirTime")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cores)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    @Html.HiddenFor(model => item.TimeId)
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cores)
        </td>
        <td>
            @Html.ActionLink("Atualizar", "EditarTime", new { id = item.TimeId }) |
            @Html.ActionLink("Excluir", "ExcluirTime", new { id = item.TimeId },
                                                       new { onclick = "return confirm('Tem certeza que deseja excluir?');"})
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Voltar","ObterTimes")
</div>